.github/workflows/deploy.yml, backend/docker-compose.dev.yml, backend/docker-compose.prod.yml, backend/run.sh, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml, backend/src/main/resources/application.yml
- close #1 
---
🔊 dev환경에서는 이상태로 쓰시고 prod 환경에서는 dev를 주석처리하고 prod 주석 해제 후 사용하면 됩니다. 
main으로 merge할때는 prod를 사용하도록 바꾸면됩니다.
``` bash
echo "[dev]📦 Building Spring Boot JAR with Gradle..."
./gradlew clean build -x test
echo "[dev]🧹 Stopping and removing existing containers..."
docker-compose -f docker-compose.dev.yml down
echo "[dev]🚀 Starting Docker containers with fresh build..."
docker-compose -f docker-compose.dev.yml up --build -d
#echo "📦 Building Spring Boot JAR with Gradle..."
#./gradlew clean build -x test
#echo "🧹 Stopping and removing existing containers..."
#docker-compose -f docker-compose.prod.yml down
#echo "🚀 Starting Docker containers with fresh build..."
#docker-compose -f docker-compose.prod.yml up --build -d # 3
```
=> Github Actions 기반 CI/CD 파이프라인 구축 및 환경별 설정 파일 분리 적용

.github/workflows/deploy.yml, backend/run.sh
- close #12 
- 🔥 workflow가 실패한 원인별로 정리하자면,
- docker-compose.prod.yml 파일을 SCP방식으로 repository(GitHub)에서 EC2 서버로 복사해오는 과정 누락
- docker-compose 명령어 오류, docker compose로 변경
- docker-compose.prod.yml의  DOCKER_USERNAME .env에 추가 
- 👍 개선한 내용
- docker pull하기전에  `docker image prune -a -f`  을 추가하여 기존 이미지 혹은 사용하지 않은 이미지 파일을 정리합니다.
- 기존 코드에서는 현재 Spring 이미지가 502MB인데 (개발 진행 시 더 늘어남) N개씩 늘어나는 문제점을 해결 했습니다.
=> refactor: deploy.yml 변경

backend/build.gradle, backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java, backend/src/main/java/com/passtival/backend/global/swagger/OpenApiConfig.java
Swagger 도입과, 팀 내 Swagger 컨벤션을 규격화 했습니다. 팀원분들은 PR 내용을 인지하며, 궁금한점이 있으면 코멘트 달아주시면 성실히 답하겠습니다.
- close #23 
**RaffleController**에 대해 Swagger(OpenAPI 3) 명세서 어노테이션을 다음과 같이 작성하였습니다.
- 클래스 단위 설명
- @Tag 어노테이션을 이용해 컨트롤러 전체에 대한 설명을 추가합니다.
- 엔드포인트별 상세 명세
- 각 API 메서드마다 @Operation 어노테이션을 통해 주요 기능 요약(summary)과 상세 설명(description)을 작성합니다.
- 파라미터가 필요한 API의 경우 @Parameter 어노테이션을 활용하여 파라미터 명, 설명, 필수 여부, 예시값 등을 명확히 기재하였습니다.
- 이때 참고자료를 통해, Path 파라미터와 쿼리파라미터 작성법을 참고하세요. 
- Request Body를 요구하는 엔드포인트는 @io.swagger.v3.oas.annotations.parameters.RequestBody, @Content, @Schema,
- @ExampleObject 등을 적용해 요청 예시와 구조를 명확히 표현하였습니다.
- 응답 및 예외 상황
- 각 API의 정상 동작뿐 아니라, 예외 발생 시의 응답 예시 및 메시지 흐름을 명확히 파악할 수 있도록 하였습니다.
- 작성 수준
- 컨트롤러 내 모든 엔드포인트에 Swagger 어노테이션을 적용.
- 기본적인 설명뿐만 아니라, 파라미터/RequestBody 예시까지 포함하여 실제 프론트엔드, QA, 문서 사용자들이 …
=> feat: Swagger 기능

backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java, backend/src/main/java/com/passtival/backend/domain/raffle/service/PrizeService.java, backend/src/main/java/com/passtival/backend/domain/raffle/service/RaffleService.java, backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java, backend/src/main/java/com/passtival/backend/global/exception/BaseException.java, backend/src/main/java/com/passtival/backend/global/handler/GlobalExceptionHandler.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml
예외 처리 표준화를 위해 BaseException 계층과 GlobalExceptionHandler를 도입했습니다.
전역 예외 처리로 일관된 응답 포맷(BaseResponse)를 보장하고, logging/trace를 강화했습니다.
컨트롤러/서비스 비즈니스 로직 변경 없이 기존 try-catch 방식을 GlobalExceptionHandler의 책임으로 위임했습니다.
logging 설정내 hibernate 로그를 제거했습니다.
- close #22 
- BaseException 계층 추가
- BaseException: 공통 필드(code, message)와 생성자 추가
- 도메인/상황별 커스텀 예외 확장 가능
- BaseResponseStatus와 Mapping을 통해 코드/메시지 일관성 유지
- GlobalExceptionHandler 추가(@RestControllerAdvice)
- BaseException 처리: BaseResponse.fail(status)로 표준 응답 반환
- Validation 예외(MethodArgumentNotValidException, ConstraintViolationException) 처리
- IllegalArgumentException, RuntimeException, Exception 등 공통 하위 예외 처리
- 예외별 로깅 레벨 차등 적용 ( `warn` vs `error` )
추가로 festival, phonMetting 도메인 별, 커스텀 에러코드를 확장하며 개발하면 됩니다.
- [ x 커밋 …
=> feat: 전역 예외처리

backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java, backend/src/main/java/com/passtival/backend/domain/lostfound/model/response/FoundItemResponse.java, backend/src/main/java/com/passtival/backend/domain/lostfound/service/LnfService.java
분실물 관련 `GET` API를 구현했습니다.
- close #51 
=> feat: 분실물 조회 API

backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java, backend/src/main/java/com/passtival/backend/domain/festival/performance/model/response/PerformanceDetailResponse.java, backend/src/main/java/com/passtival/backend/domain/festival/performance/repository/PerformanceRepository.java, backend/src/main/java/com/passtival/backend/domain/festival/performance/service/PerformanceService.java
=> fix: 공연이름으로 조회 -> id로 조회 #24

backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothController.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothDetailResponse.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/service/BoothService.java
=> fix: 부스이름으로 조회 -> id로 조회 #35

backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java
파일명에 한글 입력 기능 추가, 확장자 추가했어요.
아이폰은 heic, 안드로이드는 , jpg인데, webp도 혹시몰라 추가했습니다.
- close #70 
=> refactor: PresignURL 파일명, 확장자 형식 추가 #70 to dev

backend/src/main/resources/application.yml
=> refactor: profiles 인자 제거 #73 to dev

backend/src/main/java/com/passtival/backend/domain/matching/controller/MemberLoginController.java, backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
클라이언트에게 Get 요청을 받고 카카오톡의 로그인 화면을 리다이렉트한다.
- close #80 
=> feat: 소셜 로그인의 리다이렉트 구현

backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java, backend/src/main/java/com/passtival/backend/domain/lostfound/service/LnfService.java, backend/src/main/java/com/passtival/backend/global/s3/controller/S3Controller.java, backend/src/main/java/com/passtival/backend/global/s3/service/S3Service.java
- close #92 
- [] 변경 사항에 대한 테스트를 했습니다.
=> Refactor: lnf에서 S3 기능 S3(global)로 적재 #92

backend/src/main/java/com/passtival/backend/domain/raffle/controller/PrizeController.java, backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java
=> Refactor: 상품 관련 로직 분리 #94

backend/src/main/java/com/passtival/backend/domain/admin/controller/AdminAuthController.java, backend/src/main/java/com/passtival/backend/domain/admin/service/AdminAuthService.java, backend/src/main/java/com/passtival/backend/domain/matching/controller/MatchingController.java, backend/src/main/java/com/passtival/backend/domain/matching/controller/MemberController.java, backend/src/main/java/com/passtival/backend/domain/matching/controller/test/AuthTestController.java, backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java, backend/src/main/java/com/passtival/backend/global/handler/CustomAuthenticationFailureHandler.java, backend/src/main/java/com/passtival/backend/global/handler/OAuth2SuccessHandler.java, backend/src/main/java/com/passtival/backend/global/security/controller/TokenController.java, backend/src/main/java/com/passtival/backend/global/security/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/passtival/backend/global/security/filter/LoginFilter.java, backend/src/main/java/com/passtival/backend/global/security/model/AuthUserDto.java, backend/src/main/java/com/passtival/backend/global/security/model/CustomMemberDetails.java, backend/src/main/java/com/passtival/backend/global/security/model/CustomOAuth2User.java, backend/src/main/java/com/passtival/backend/global/security/model/KakaoResponse.java, backend/src/main/java/com/passtival/backend/global/security/model/Oauth2Response.java, backend/src/main/java/com/passtival/backend/global/security/model/token/RefreshTokenRequest.java, backend/src/main/java/com/passtival/backend/global/security/model/token/TokenResponse.java, backend/src/main/java/com/passtival/backend/global/security/service/CustomMemberDetailsService.java, backend/src/main/java/com/passtival/backend/global/security/service/CustomOAuth2UserService.java, backend/src/main/java/com/passtival/backend/global/security/service/TokenService.java, backend/src/main/java/com/passtival/backend/global/security/util/JwtUtil.java, backend/src/main/java/com/passtival/backend/global/security/util/ResponseUtil.java
- rename auth to security
- 인증/인가가 아닌, security 전반을 관리하므로 변경
- rename AuthService to TokenService
- Service 로직이 모두 Token관련 로직이라 변경
- rename AuthController to TokenController
- Controller 로직이 모두 Token관련 로직이라 변경
- close #96 
- [] 변경 사항에 대한 테스트를 했습니다.
=> Refactor: auth 폴더 개선 #96

backend/docker-compose.dev.yml, backend/docker-compose.prod.yml, backend/src/main/resources/application-prod.yml
- close #107 
nginx 프록시 설정 - https 설정 완료
docker compose 파일 내, 보안그룹에서 nginx를 통한 경로만 허용
=> Feat: nginx 프록시 설정, 바인딩 설정 #107

backend/.env.example, backend/build.gradle, backend/docker-compose.dev.yml, backend/src/main/resources/application-dev.yml
=> Redis 제거, 배포환경 RDS 연동

backend/src/main/java/com/passtival/backend/domain/festival/menu/model/response/MenuResponse.java
응답값에 menuId추가
> 현재 상황을 몰라 확인 후에 머지해도 괜찮으면 바로 머지하겠습니다.
- close #126
=> menu응답 값 id추가

backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java, backend/src/main/java/com/passtival/backend/global/security/controller/BlockController.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml
기존 방식으로 차단을 하려고 하니까 패턴 파서 에러가나서 서버가 꺼진다.
문제 해결  -> 패턴 방지를 컨트롤러에서 해버린다. 이미지 같이 나오고 알람 안 울림
- close #135 
=> fix: 컨트롤러에서 리다이렉트 시키는 방식으로 해결 #135

backend/docker-compose.prod.yml
EC2 환경에서 RDS로 DB를 이전했지만 docker-compose 파일을 수정하지 않아 여전히 mysql이 켜진 문제를 해결했습니다.
- close #142 
=> refactor: 운영환경 Docker-compose.prod Redis, MySQL 제거 #142

backend/src/main/java/com/passtival/backend/domain/member/model/entity/request/LevelUpRequest.java
- close #174 
@Valid를 이용해, 이름(필수), 학번(1234A5678 형식), 인증키(필수) 설정을 추가했습니다.
=> feat: Level-up 시 Valid 유효성 검증

backend/src/main/java/com/passtival/backend/domain/member/controller/MemberController.java, backend/src/main/java/com/passtival/backend/domain/member/model/entity/request/LevelUpRequest.java
=> [Fix] 학번, 이름 유효성 검증 추가

backend/src/main/java/com/passtival/backend/domain/festival/booth/repository/BoothRepository.java
부스 id값이 1부터 27 순으로 조회되도록 변경
- close #194
내림차순 -> 오름차순으로 변경 id값이 1 -> 34로 조회
=> [Refactor] 부스 커서 정령 오름차순

backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java, backend/src/main/java/com/passtival/backend/domain/festival/performance/service/PerformanceService.java
시간순으로 정렬이 되지않는 코드 수정
- close #203
=> [Feat] 공연 시간순 정렬

backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
스웨거, Test컨트롤러 권한 수정을 통해 보안 사고 방지
- close #216
```
// 수정 전
.requestMatchers("/swagger-ui/**", "/v3/api-docs/**", "/swagger-ui.html").permitAll()
.requestMatchers("/api/test/**").permitAll()
// 수정 후
.requestMatchers("/swagger-ui/**", "/v3/api-docs/**", "/swagger-ui.html").hasRole("ADMIN")
.requestMatchers("/api/test/**").hasRole("ADMIN")
```
기타 주석도 조금 정리했어요!
=> refactor: 스웨거, Test컨트롤러 권한 수정

backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothController.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/model/entity/Booth.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothDetailResponse.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/repository/BoothRepository.java, backend/src/main/java/com/passtival/backend/domain/festival/booth/service/BoothService.java
부스의 위치 속성을 추가하여 부스 위치가 밀림에도 db값 변경하기 쉽게 하기 위함
- close #219
=> [Feat] 부스 위치id 속성 추가

backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java, backend/src/main/resources/application-prod.yml
=> fix: swagger 비활성화

backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java, backend/src/main/resources/application-prod.yml
=> hotfix: 스웨거 활성화

backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java
=> hotfix: location_id 응답에서 제거

backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java
=> hotfix: location_id 응답에서 추가
